import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "@/ui/organisms/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${inter.className} container`}>
				<Header />
				<main className="container mx-auto mb-20 mt-5 p-3 sm:p-12 lg:max-w-7xl">
					{children}
				</main>
				<footer className="fixed bottom-0 w-screen bg-white p-3 text-center">
					&copy; 2023 Next13Masters
				</footer>
			</body>
		</html>
	);
}
